### PR TITLE
Fix #930

### PR DESCRIPTION
**Pull request by rightx2**
### Pull Request Description
Fix #930 . There might be a misunderstanding.

### CODE REVIEW

**Comment by rightx2** [comment]
@jeff-hernandez  Hi, Thanks for trying fixing this up. However, you are missing a point. The feature value on the EXACT cutoff time point should not be included when calculating feature generation for that cutoff time. Let's go back to the issue that I raised: 

> So, 1 month amount aggregation period: 2012-03-01 ~ 2012-03-31, March, 2012. Let's see SUM(sales.amount) column value of (store_id = 0 & 2012-03-01 cutoff time). The value is 44 by adding up the amounts of 2012-02-05, 2012-02-10, and """2012-03-01"""!!!. It counts """2012-03-01"""  here again, which is a sort of cheating and look-ahead bias` 

As I said here, "2012-03-01" should be not counted when calculating features for the cutoff time of "2012-03-01".  But your pull request doesn't solve this problem. Therefore, I've fixed it with a new pull request

**Comment by jeff-hernandez** [comment]
Hi @rightx2, thanks for reaching out. Featuretools always includes the feature value [on the exact cutoff time](https://docs.featuretools.com/en/stable/automated_feature_engineering/handling_time.html#what-is-the-cutoff-time). If you want to calculate a one month training window, you can adjust the cutoff times to be the last day of the month instead of the first day of the following month and use a `MonthEnd` training window.


```python
from pandas.tseries.offsets import MonthEnd

cutoff_time - MonthEnd()
```

```
id
0   2012-02-29
1   2012-03-31
2   2012-02-29
3   2012-03-31
4   2012-02-29
5   2012-03-31
6   2012-02-29
7   2012-03-31
Name: cutoff_time, dtype: datetime64[ns]
```

**Comment by rightx2** [comment]
@jeff-hernandez  Hmm. I don't understand why do you guys make it "includes the feature value on the exact cutoff time"... It doesn't look logically make sense to me...

1. Let say I have to predict 1month revenue for each store. Then I have to predict the revenue from 2020-03-01 00:00:00 ~ 2020-03-31 23:59:59, using the data from the past ~ 2020-02-29 23:59:59 (This time split is not overlapped), right?

2. But your instruction is the way of predicting "2020-03-01 00:00:00 ~ 2020-03-31 23:59:59" using "past ~ 2020-03-01 00:00:00" feature data, which seems not logically making sense because it counts the time of future and make time overlapped.

3. Moreover, if I followed your instruction, using `MonthEnd()`, I would miss the feature data of "2020-02-29 15:23" or "2020-02-29 22:23", because the cutoff time is "2020-02-29", which is 00:00:00.

4. Consequently, what I have to do is `cutoff_time - pd.Timedelta(seconds=1)` to handle above situation, which is so bothering and confusing for the beginner.

Am I missing something? Could you tell me the situation that your instruction, logic works well more generally?

**Comment by jeff-hernandez** [comment]
@rightx2 thanks for sharing your feedback. After considering this, we do think it makes sense to let users choose whether data at exact cutoff times should be included in feature calculations. We plan to provide this option as a parameter in DFS. You can find more information about this parameter at #942. Let me know if you have additional feedback. Thanks.

**Comment by rightx2** [comment]
@jeff-hernandez That would be nice :)  Is there any way I can contribute?

**Comment by rightx2** [comment]
I'd like to participate in solving this issue as well

**Comment by jeff-hernandez** [comment]
@rightx2 yes, any contributions are helpful and greatly appreciated. [This page](https://github.com/FeatureLabs/featuretools/blob/master/contributing.md) has helpful information and instructions for contributing. You can participate to solve this issue as well. Would you like to submit a pull request for #942?

**Comment by rightx2** [comment]
@jeff-hernandez  Ok, I will try

**Comment by jeff-hernandez** [comment]
Okay, sounds good. I will update #942 with any details about the implementation or test cases as they come up.

**Comment by rwedge** [comment]
Closing in favor of other pr #959

**Pull request closed without merging**
