### PR TITLE
Fix hyperlinks in docs and docstrings with updated address

### PR DESCRIPTION
**Pull request by gsheni**
### Pull Request Description
- The ecosystem is incorrect and doesn't currently work. This PR fixes that. 
- There are additional links which have the same problem, and this PR addresses that.

### CODE REVIEW

**Comment by rwedge** [comment]
Can you do a sweep for any other links that references specific pages on docs.featuretools.com and are missing the `/en/stable/` part of the path?

**Comment by gsheni** [comment]
> Can you do a sweep of the repo for any other links that references specific pages on docs.featuretools.com and are missing the `/en/stable/` part of the path?

There was 2 more in the docstrings that I fixed.

**Comment by rwedge** [comment]
I think there's another link in `docs/source/templates/layout.html` that needs to be fixed

**Comment by gsheni** [comment]
> I think there's another link in `docs/source/templates/layout.html` that needs to be fixed

Fixed. 

I thought changing the link would not work since it was a static image. So I skipped it on my review. But the new link worked.

**Pull request merged**
