### PR TITLE
include datetime.date in wrangle._check_time_type validation

### PR DESCRIPTION
**Pull request by RogerTangos**
- add a check for datetime.date in wrangle._check_time_type, solving issue #105

### CODE REVIEW

**Comment by RogerTangos** [comment]
@kmax12

**Comment by RogerTangos** [comment]
Hey - I'll fix this up (or withdraw the PR if I can't) later on. Sorry for the delay.

**Comment by kmax12** [comment]
@RogerTangos no problem. if you hit any issues - send us a message on gitter and we can help: https://gitter.im/featuretools/featuretools

**Comment by kmax12** [comment]
@RogerTangos the errors you're seeing are probably related to pandas releasing 0.23.0 last week. we're looking into updating featuretools to support 0.23.0 now, which should clean up the testing errors you're after you merge our fixes in. thanks for the patience!

**Comment by bschreck** [comment]
@RogerTangos we just merged in a fix to master that makes it compatible with the new version of Pandas. If you merge your branch with master, the tests should pass.

**Comment by RogerTangos** [comment]
Hey @bschreck, I believe my branch was up to date, but it does look like a pandas issue. Could you try triggering a rebuild and seeing what happens?

**Comment by kmax12** [comment]
@RogerTangos you're right that it was a pandas issue. it's was fixed in master after you created this branch. can you merge master in your branch? that will retrigger a build and the tests should pass.

**Comment by RogerTangos** [comment]
Hey @kmax12 - Sorry for the late reply. Its been a while since I last touched that notebook. I'll pull it up again, and see if I can recreate the error and/or share it

**Comment by rwedge** [comment]
Closing this PR for now.  Will re-open if there is a reproducible example

**Pull request closed without merging**
