### PR TITLE
Removing type casting in Equals and NotEquals Primitives

### LINKED ISSUE #500: Loading previously saved features: ValueError: cannot convert float NaN to integer
Not sure whether this is a bug or I am doing something incorrectly, but:

assume the feature matrix is created as in all of the example documentation:

```
feature_matrix, feature_defs = ft.dfs(entityset = es,
                                      target_entity = "test",
                                      agg_primitives = ["mean","min","median"],
                                      verbose = True,
                                      n_jobs = 1,
                                      max_depth = 2)
```

this is working fine and I am able to save and export these features without any problems.

However, if we want to move this into production the following workflow breaks:

1. Storing created features:
```
feature_matrix_enc, features_enc = ft.encode_features(feature_matrix, feature_defs)
```
2. Creating file for the export:
```
ft.save_features(features_enc, "feature_definitions")
```
3. Loading the features (for the test case - nothing _actually_ changes, same live environment):
```
saved_features = ft.load_features("feature_definitions")
```
4. Transforming them back, using the same entity ``es`` that was used to create the features:
```
feature_matrix = ft.calculate_feature_matrix(saved_features, es)
```
However, the last step returns the following error:

```
...

  File "pandas\_libs\lib.pyx", line 456, in pandas._libs.lib.astype_intsafe

  File "pandas/_libs/src\util.pxd", line 142, in util.set_value_at_unsafe

ValueError: cannot convert float NaN to integer
```

Is there a way to fix this? If the original feature matrix was created despite those NaN values, can we ignore them on load? Or am I missing something?

Big thanks!

### PR DESCRIPTION
**Pull request by kmax12**
We were doing the casting to be careful, but there is no need because pandas will handle it internally

This should fix #500 and #496

### CODE REVIEW

**Comment by kmax12** [comment]
This is appears to be the problem here: https://stackoverflow.com/questions/57601595/how-to-write-seed-features-that-work-with-cutoff-time?noredirect=1#comment101752737_57601595

**Comment by levng** [comment]
This PR fixes the problem! The `ValueError: Cannot convert non-finite values (NA or inf) to integer` error no longer occurs and the features are built without a hitch.

**Comment by apemann** [comment]
Can this fix make it into the next release please? It looks like it's almost done.

**Comment by apemann** [comment]
Thank you @rwedge and @kmax12!

**Pull request merged**
