### PR TITLE
Fix ft.show_info() doesn't work in Jupyter(#650)

### PR DESCRIPTION
**Pull request by FreshLeaf8865**
### Pull Request Description
Fix the issue that ft.show_info() doesn't work in Jupyter.

-----
*After creating the pull request: in order to pass the **changelog_updated** check you will need to update the "Future Release" section of* `docs/source/changelog.rst` *to include this pull request.*

### CODE REVIEW

**Comment by kmax12** [comment]
@FreshLeaf8865 can you sign CLA/make sure it validates?

**Comment by FreshLeaf8865** [comment]
> @FreshLeaf8865 can you sign CLA/make sure it validates?

Done!

**Comment by rwedge** [comment]
Fixes #650

**Comment by rwedge** [comment]
Hi @FreshLeaf8865 , this PR slipped through our review process, my apologies.  I've reviewed this branch and confirmed this fixes the issue.

It looks like because we moved this repo from the Featuretools org to the FeatureLabs org, the CLA assistant wants you to sign the CLA again.  Could you redo that, please?

**Comment by rwedge** [comment]
These changes were handled by #863

**Pull request closed without merging**
